### ISSUE TITLE
Cannot find latest version in Jetbrains Marketplace

### ISSUE THREAD

**Issue by Samarium150** [Him188/kotlin-jvm-blocking-bridge#13]
The latest version in Jetbrains Marketplace is still [1.7.0](https://plugins.jetbrains.com/plugin/14816-kotlin-jvm-blocking-bridge/versions)

**Comment by Him188** [comment]
That's as expected since incremental compiler updates are not necessary to the IntelliJ plugin.

**Comment by Him188** [comment]
I will upload an update for 1.7.4 to reduce confusion. Thank you.

**Comment by Samarium150** [comment]
Thanks for your response.
