### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by AdoptOSS** [Him188/kotlin-jvm-blocking-bridge#14]
Kotlin JVM Blocking Bridge is currently JCenter-only. When used without declaring JCenter repository, a resolution failure occurs:
```
Could not find net.mamoe:kotlin-jvm-blocking-bridge:1.7.4.
```

**Comment by AdoptOSS** [comment]
Related:
mamoe/mirai#970
mamoe/mirai#981

**Comment by Him188** [comment]
Thank you for the reminder. Kotlin JVM Blocking Bridge is more complex to be published. It's on the schedule.

**Comment by Him188** [comment]
Kotlin JVM Blocking Bridge may be used internationally, so I will translate your issue into English. Thanks for understanding.
